apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: coswebs.example.com
spec:
  group: example.com
  names:
    kind: Cosweb
    listKind: CoswebList
    plural: coswebs
    singular: cosweb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Cosweb is the Schema for the coswebs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CoswebSpec defines the desired state of Cosweb
          properties:
            image:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            name:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - image
          - labels
          - name
          - replicas
          type: object
        status:
          description: CoswebStatus defines the observed state of Cosweb
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
